
spring:
  application:
    name: stock-management-system

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  profiles:
    active: ${ACTIVE_PROFILE:dev}


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stock_management_system}
    username: ${SPRING_DATASOURCE_USERNAME:hels}
    password: ${SPRING_DATASOURCE_PASSWORD:hels}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #hhibernate  ddl auto (create,create-drop,update
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.springframework: DEBUG

#####################################################################################3

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}

    properties:
      mail:
        mine:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${SMTP_SSL_TRUST}
    verify:
      host: ${VERIFY_EMAIL_HOSt}


#####################################################################################3
# Configuration MinIO pour la gestion des photos
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:stock-photos}
  init:
    enabled: ${MINIO_INIT_ENABLED:false}

#Configuration JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}


server:
  port: 8081