
spring:
  application:
    name: stock-management-system

  springdoc:
    swagger-ui:
      path: /swagger-ui.html



  datasource:
    url: jdbc:postgresql://localhost:5432/stock_management_system
    username: hels
    password: hels
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #hhibernate  ddl auto (create,create-drop,update
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.springframework: DEBUG


server:
  port: 8081