
spring:
  application:
    name: stock-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_management
    username: hels
    password: hels
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #hhibernate  ddl auto (create,create-drop,update
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081