#database
#POSTGRES_SQL_HOST: localhost
#POSTGRES_SQL_PORT: 5432
#POSTGRES_SQL_DB: gestion_clinic
#POSTGRES_SQL_USERNAME: hels
#POSTGRES_SQL_PASSWORD: hels

#SERVER
SERVER_PORT: 8080


ACTIVE_PROFILE: dev



SMTP_HOST: smtp.gmail.com
SMTP_PORT: 587
SMTP_USER: m7hels@gmail.com
SMTP_PASSWORD: rssn mtuw blbk qara
SMTP_SSL_TRUST: smtp.gmail.com
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}

#security
JWT_SECRET_KEY: F06PBJ6GzaTRCyiAycvwVHn0Mkgi9ztGpl6DIkULwtDcJ2y17uDwYS0XdrNjIIfWKAvWPoyAwBLHvHKnDzzPmmXWEpaRbWVG8zGkIViUWumw64U6nGOE2d5a7Zb9sQaOrmYfxCHTbPinjbSOoMuSJhk793ewS3COygGtNoAKjGZgiwzlWpIgAYDxTDHzJAL6gp8YEuxmq5CpovVtTm6V4hvEf3kA7zBmjWctjTULcXlQ2VjfhH6WI48lJ5gqBZWl
JWT_EXPIRATION: 86400000    # 24 heures en millisecondes