
spring:
  application:
    name: stock-management-system

  springdoc:
    swagger-ui:
      path: /swagger-ui.html



  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stock_management_system}
    username: ${SPRING_DATASOURCE_USERNAME:hels}
    password: ${SPRING_DATASOURCE_PASSWORD:hels}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #hhibernate  ddl auto (create,create-drop,update
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.springframework: DEBUG

# Configuration MinIO pour la gestion des photos
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:stock-photos}
  init:
    enabled: ${MINIO_INIT_ENABLED:false}

server:
  port: 8081